name: alan
description: Pure Dart library to easily integrate with any Cosmos-based chain.
version: 0.40.2+1
homepage: https://github.com/alan-sdk/alan.dart
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  asn1lib: ^1.1.0
  bech32: ^0.2.1
  bip39: ^1.0.6
  convert: ^3.0.2
  equatable: ^2.0.3
  fixnum: ^1.0.1
  grpc: ^3.0.2
  hex: ^0.2.0
  http: ^0.13.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  meta: ^1.7.0
  pointycastle: ^3.6.0
  protobuf: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  mockito: ^5.2.0
  mock_web_server: ^5.0.0-nullsafety.1
  pedantic: ^1.11.1
  test: ^1.21.4
